# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/loganalyzer?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Batch 메타 테이블 자동 생성
spring.batch.initialize-schema=always

# 로그
logging.level.com.loganalyzer=INFO
